-- Game Seasons
CREATE TABLE IF NOT EXISTS game_seasons (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    start_time INTEGER,
    end_time INTEGER,
    global_target INTEGER DEFAULT 1000000,
    current_progress INTEGER DEFAULT 0,
    status TEXT DEFAULT 'ACTIVE',
    created_at INTEGER,
    updated_at INTEGER
);

-- Game World State (Daily Snapshot)
CREATE TABLE IF NOT EXISTS game_world_state (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    season_id TEXT,
    date TEXT, -- YYYY-MM-DD
    chaos_level INTEGER DEFAULT 0,
    market_stability INTEGER DEFAULT 100,
    daily_news_summary TEXT, -- Generated by AI
    created_at INTEGER,
    FOREIGN KEY (season_id) REFERENCES game_seasons(id)
);

-- Initial Season Data
INSERT OR IGNORE INTO game_seasons (id, name, description, start_time, end_time, global_target, current_progress, status, created_at, updated_at)
VALUES 
('season_01', 'Season 1: The Genesis Signal', 'A mysterious signal from the deep web has activated ancient protocols. Collect Signal Fragments to decode the message.', strftime('%s','now'), strftime('%s','now', '+90 days'), 1000000, 4200, 'ACTIVE', strftime('%s','now'), strftime('%s','now'));

-- Initial World State
INSERT OR IGNORE INTO game_world_state (season_id, date, chaos_level, market_stability, daily_news_summary, created_at)
VALUES 
('season_01', date('now'), 15, 95, 'BREAKING: Anomalous energy readings detected near Sector 7. The Archivist reports increased data corruption in Amsterdam port logs. Pilots are advised to exercise caution when navigating the outer rim.', strftime('%s','now'));
