package com.soulon.app.storage

import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Test
import java.nio.ByteBuffer
import java.nio.ByteOrder

class ArweaveDataItemTest {

    @Test
    fun testCreateSolanaDataItemStructure() = runBlocking {
        // Arrange
        val data = "Hello Irys".toByteArray(Charsets.UTF_8)
        val publicKey = ByteArray(32) { 1 } // 32 bytes of 0x01
        val signature = ByteArray(64) { 2 } // 64 bytes of 0x02
        
        val tags = listOf(
            ArweaveDataItem.Tag("App-Name", "Soulon"),
            ArweaveDataItem.Tag("Version", "1.0")
        )

        // Act
        val dataItem = ArweaveDataItem.createSolanaDataItem(
            data = data,
            publicKey = publicKey,
            tags = tags,
            signFunction = { _ -> signature }
        )

        // Assert - Parse the binary manually to verify ANS-104 compliance
        val buffer = ByteBuffer.wrap(dataItem).order(ByteOrder.LITTLE_ENDIAN)

        // 1. Signature Type (2 bytes)
        val sigType = buffer.short
        assertEquals("Signature type should be 2 (Solana)", 2.toShort(), sigType)

        // 2. Signature (64 bytes)
        val sigBytes = ByteArray(64)
        buffer.get(sigBytes)
        assertArrayEquals("Signature should match", signature, sigBytes)

        // 3. Owner (32 bytes)
        val ownerBytes = ByteArray(32)
        buffer.get(ownerBytes)
        assertArrayEquals("Owner (PublicKey) should match", publicKey, ownerBytes)

        // 4. Target flag (1 byte)
        val targetFlag = buffer.get()
        assertEquals("Target flag should be 0", 0.toByte(), targetFlag)

        // 5. Anchor flag (1 byte)
        val anchorFlag = buffer.get()
        assertEquals("Anchor flag should be 0", 0.toByte(), anchorFlag)

        // 6. Tags Count (8 bytes) - THIS WAS THE FIX
        val tagsCount = buffer.long
        assertEquals("Tags count should match", tags.size.toLong(), tagsCount)

        // 7. Tags Bytes (8 bytes) - THIS WAS THE FIX
        val tagsBytesLength = buffer.long
        
        // 8. Tags Payload
        val tagsPayload = ByteArray(tagsBytesLength.toInt())
        buffer.get(tagsPayload)
        // (We assume Avro encoding logic inside is correct if it generated bytes, 
        // mainly checking the header structure here)

        // 9. Data
        val remainingBytes = ByteArray(buffer.remaining())
        buffer.get(remainingBytes)
        assertArrayEquals("Data should match", data, remainingBytes)
        
        println("✅ ANS-104 Header Structure Verified")
        println("Tags Count: $tagsCount")
        println("Tags Bytes: $tagsBytesLength")
    }
}
